[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'foundry_test'
cache_path  = 'forge-cache'
max_test_rejects = 10000000
# See more config options https://book.getfoundry.sh/reference/config.html