[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'foundry_test'
cache_path  = 'forge-cache'

# See more config options https://book.getfoundry.sh/reference/config.html
[fuzz]
max_test_rejects=2147483647
