[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'foundry_test'
cache_path  = 'forge-cache'
memory_limit = 43554432

# See more config options https://book.getfoundry.sh/reference/config.html
[fuzz]
runs = 20
max_test_rejects=2147483647
