name: solhint-ci
on: [pull_request]
jobs:
  solhint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - run: |
          yarn install --frozen-lockfile
          echo "$(yarn global bin)" >> $GITHUB_PATH
          solhint 'packages/contracts/contracts/*.sol'
